### PR TITLE
Change namespace package imports and update answers after updated sun position calculation

### PR DESCRIPTION
**Pull request by jzuhone**
## Description

This PR changes all "namespace" package imports to their new names. It also contains a follow-on to https://github.com/sot/ska_sun/pull/36 which changed the default method of changing the sun position calculation, making it more accurate. This necessitated an update to the answers for the regression tests, which only had minor changes due to this update.

## Interface impacts

None

### Unit tests

- [ ] No unit tests
- [ ] Mac
- [x] Linux
- [ ] Windows

Independent check of unit tests by [REVIEWER NAME]
- [ ] [PLATFORM]:

### Functional tests

No functional testing.

### CODE REVIEW

**Review by taldcroft — APPROVED** [review]
LGTM. Namespace package updates are good. I spot-checked the "answers" diffs for one states file and see expected diffs: small changes in pitch and changes in maneuver attitude quaternions at the 12th decimal place. The latter is likely from using numba not numpy, but in any case is inconsequential.

**Comment by jeanconn** [comment]
The updates look good to me.  I'd like to run the unit and regression tests but is there a recommended way to do so without installing the module?  If I try to run pytest or `python setup.py test` from the repo I just get those `E           AttributeError: 'Namespace' object has no attribute 'test_root'` errors.

**Comment by jzuhone** [comment]
@jeanconn from the top-level directory run `py.test acis_thermal_check/tests/dpa` for the 1DPAMZT tests

**Review by Gregg140 — APPROVED** [review]
Namespace changes look good

**Pull request merged**
