### PR TITLE
Flag both hot and cold violations for DPA board component temperatures, fix a bug in the reporting of focal plane violations

### PR DESCRIPTION
**Pull request by jzuhone**
This PR does two things:

1. It sets up a framework for plotting and reporting violations of the _low_ planning limits as well as the high planning limits. This new behavior will only be executed for model runs of the DPA board component temperatures (FEP and BEP models), since we now plan to run frequently with 0 FEPs and we would like to be alerted if a particular model run will elicit such behavior (this is very unlikely, but probably a good thing to check). 

One other thing we would like to be able to do which follows from this is determine the model accuracy for low temperatures as well as high ones, which involves making histograms of error for low temperatures similar to those which are already made for high temperatures. Similar to the multiple histograms for the PSMC model, which are made for two values of a high temperature, we can overlay these histograms on the same plot. However, in these cases the histograms correspond to the low and high temperatures. 

Changes for the FEP1 Mongoose model, where we have reporting of both potential hot and cold violations, new lines for the cold limits, and two histograms:

Old: http://cxc.cfa.harvard.edu/acis/FEP1_MONG_thermPredic/FEB1218/oflsa/

New: http://cxc.cfa.harvard.edu/acis/tmp/fix_viols/test_feb1218a_fep1_mong/

For the DPA model (and the other 3 historical models), we expect no reporting of cold violations, but the design of the histograms does change:

Old: http://cxc.cfa.harvard.edu/acis/DPA_thermPredic/FEB1218/oflsa/

New: http://cxc.cfa.harvard.edu/acis/tmp/fix_viols/test_feb1218a_dpa

Same for the PSMC model, which already had two histograms:

Old: http://cxc.cfa.harvard.edu/acis/PSMC_thermPredic/FEB1218/oflsa/

New: http://cxc.cfa.harvard.edu/acis/tmp/fix_viols/test_feb1218a_psmc

2. The `acisfp_check` software, which runs the ACIS focal plane model, reported a violation of the temperature for a focal-plane-sensitive observation (obsid 20971) for the `FEB1918A` load:

http://cxc.cfa.harvard.edu/acis/FP_thermPredic/FEB1918/oflsa/

Inspection of the violation information shows that the violation lasted for three days(!), which is obviously longer than any observation these days, and inspection of this obsid shows it lies entirely _before_ the load under review. It turns out that this is caused by a bug which did not properly take the load start into account for the focal plane model. This PR fixes the bug. It also changes the way violations for specific obsids are reported, in the sense that each temperature violation is reported on a per-obsid basis. This is an improvement on the previous behavior, which 

Old and new versions of the `FEB1918A` load, showing the "violation" disappears with this PR:

Old: http://cxc.cfa.harvard.edu/acis/FP_thermPredic/FEB1918/oflsa/

New: http://cxc.cfa.harvard.edu/acis/tmp/fix_viols/test_feb1918a

Several loads with actual violations were tested also. The desired behavior is that the violations are still detected, which is what happens:

Old versions:

http://cxc.cfa.harvard.edu/acis/FP_thermPredic/JAN2218/oflsa/
http://cxc.cfa.harvard.edu/acis/FP_thermPredic/FEB1218/oflsa/
http://cxc.cfa.harvard.edu/acis/DPA_thermPredic/FEB1218/oflsa/

New versions:

http://cxc.cfa.harvard.edu/acis/tmp/fix_viols/test_jan2218a
http://cxc.cfa.harvard.edu/acis/tmp/fix_viols/test_feb1218a
http://cxc.cfa.harvard.edu/acis/tmp/fix_viols/test_feb1218a_dpa

This also requires a separate PR to `acisfp_check` (acisops/acisfp_check#12), but thankfully the result is to reduce the duplicated code even further between these two packages.

### CODE REVIEW

**Comment by taldcroft** [comment]
@jzuhone - I must be missing something silly because in the "new" plots I don't see anything that looks like the cold-temperature histograms that you describe.  (OR are there insufficient lo-temp data for a histogram?)  The only difference I see is in the style of plotting the histogram.  I also don't see any cold-limit lines in the temperature vs time plots.

In particular, look at:  http://cxc.cfa.harvard.edu/acis/tmp/fix_viols/test_feb1218a_dpa

In general it would be a good thing to show test cases where you temporarily change the low limit to something higher in order to get a low violation in the output.

**Comment by jzuhone** [comment]
Hi @taldcroft, 

Sorry--I made a mistake and didn't put the correct TMP_FEP1_MONG plot above. Here are the before and after plots showing the new histogram for the cold temperatures:

Old: http://cxc.cfa.harvard.edu/acis/FEP1_MONG_thermPredic/FEB1218/oflsa/

New: http://cxc.cfa.harvard.edu/acis/tmp/fix_viols/test_feb1218a_fep1_mong/

I did test by hand to show that if I raise the lower limit that I do get violations. If you want I can show that when I present to LRB next week.

**Comment by jeanconn** [comment]
And I've finally had a chance to look this over and the changes make sense to me.  I confess, when looking at the code using the new "low" limits, I expected to see a change in an accompanying characteristics file to store those low limits.  I see now from utils.py that those limits are managed outside the scope of this project in files on the web server.  I have forgotten the reasoning for that though... should the MSID_Limits.txt and pmon_limits.txt file just be project data added to version control in this project or a new one?  Thanks!

**Comment by jzuhone** [comment]
Hi @jeanconn,

Might be a good idea to add these files to version control somewhere, but these files are the "official" source for the ACIS limits, which is why they are being parsed by `acis_thermal_check` to obtain limits (previously the limits were hard-coded in the scripts, but the ACIS team decided to parse these files instead to avoid updating a limit officially and forgetting to do it in the software).

**Pull request merged**
