### PR TITLE
acis_thermal_check 3.0

### PR DESCRIPTION
**Pull request by jzuhone**
This PR implements a substantive update to `acis_thermal_check`, containing
mostly visualization improvements, but also reducing code duplication and
improving the accuracy of predictions. 
* Instead of using pitch from the commanded states to use in the model and
compute the off-nominal roll, calculate the pitch and off-nominal roll using the
target quaternion and the ephemeris. This provides updated pitch and roll more
often in the model and should be equivalent to what @matthewdahmer is doing when
he runs the FOT models. This improves the roll validation on the ACIS thermal
model pages. 
* Increase the size of all plots to match size of those on the focal plane page.
* Reduce duplicated code in `calc_model` between the different check tools;
allow them to perform additional operations via `_calc_model_supp`, which they
override. 
* Move the detector housing heater history file, `dahtbon_history.rdb`, to the
package instead of copying it around all of the time. 
* Swap the red and blue colors on validation plots to match FOT scheme.
* Plot FEP count on CCD count prediction plot.
* Add plots of CCD/FEP count and (optionally) Earth solid angle for validation
runs for diagnostic purposes. 
* Display the version of the check package used in `run.dat`, thanks to
`ska_helpers`. 
* Print the MD5 sum of the thermal model in `run.dat` for reproducibility purposes.
* Vastly improved testing suite with answers locally stored in the various check tools.

Verification plots are forthcoming. This will require updates to the various
ACIS thermal model check tools as well.

### CODE REVIEW

**Comment by jzuhone** [comment]
@jazan12 the 2098 is basically to make sure that the state previous to that holds till whenever.

**Comment by jzuhone** [comment]
@taldcroft and @matthewdahmer I found the issue with the pitch and fixed it in commit 5fa3d80. This is ready for review now.

**Comment by taldcroft** [comment]
@jzuhone - can you include a plot of the new pitch deviations (states vs actual)?  Apart from that I skimmed the code quickly but would not claim as code review.  I'm happy with the presentation though and review by @jazan12, as long as the pitch plot is OK.

**Comment by jzuhone** [comment]
@taldcroft I redid the web pages that I showed at the TWG, here they are now, which show the improved pitch plots:

1DPAMZT: [current](https://cxc.cfa.harvard.edu/acis/DPA_thermPredic/MAR0920/oflsa/) [new](https://cxc.cfa.harvard.edu/acis/Thermal/tmp/dpa_MAR0920/)

ACIS FP: [current](https://cxc.cfa.harvard.edu/acis/FP_thermPredic/MAR0920/oflsa/) [new](https://cxc.cfa.harvard.edu/acis/Thermal/tmp/fp_MAR0920/)

**Comment by matthewdahmer** [comment]
Thank you for posting the new web pages reflecting the fix to the pitch calculations!

**Pull request merged**
