### PR TITLE
Move all of the temperature model scripts into the main package

### PR DESCRIPTION
**Pull request by jzuhone**
## Description

This PR moves all of the individual thermal model tools which depend on `acis_thermal_check`, such as `dea_check`, `acisfp_check`, etc., which currently reside in their own packages and github repositories.

This looks incredibly daunting--~over 300 changed files! But most of them are the files which have been added in (scripts, tests, answers) as a result of moving the scripts in. The essential files to review are `main.py`, `state_builder.py`, `utils.py`, `index_template.rst`, `regression_testing.py`, and `setup.py`.

This PR also makes the other changes:

* Use `get_xija_model_spec` to get the model specification file
* Use pathlib instead of os.path
* Print "hot" ACIS-S observations to the thermal model webpage
* Change name of SQLStateBuilder to KadiStateBuilder (no functional changes)
* Minor changes to support the above as needed
* Support eclipses for model predictions using kadi states

The regression tests which originally resided in the separate packages all passed after moving them to the new package, with minor modifications to the code (changing paths, etc.) but no changes to test answers were necessary. At the end of the development process, when eclipse states were added, this required an update to the test answers. The changes to the test answers were examined and consistent with the adding of eclipses.

A test run of the ACIS "LR" software confirmed that the executable path will not need to be changed once the new ``acis_thermal_check`` package is installed.

After the new version of acis_thermal_check is installed in ska, we will need to uninstall the old packages (`dpa_check`, etc.). I will work with @javierggt , @taldcroft, and @jeanconn to figure this out. 

## Testing

- [x] Passes unit tests on MacOS, linux, Windows (at least one required)
- [x] Functional testing

### CODE REVIEW

**Comment by jzuhone** [comment]
A built version of the docs is here:

https://cxc.cfa.harvard.edu/acis/acis_thermal_check_dev/

**Review by Gregg140 — APPROVED** [review]
Looks ok to me.

**Review by jazan12 — APPROVED** [review]
The 6 files in question look ok to me.

**Comment by javierggt** [comment]
Before you merge this, I would like to know how to update Ska tests, so I can update them quickly. Tests are currently defined in the `test_*` files in:
- https://github.com/sot/ska_testr/tree/master/packages/dpa_check
- https://github.com/sot/ska_testr/tree/master/packages/dea_check
- https://github.com/sot/ska_testr/tree/master/packages/acisfp_check
- https://github.com/sot/ska_testr/tree/master/packages/bep_pcb_check
- https://github.com/sot/ska_testr/tree/master/packages/fep1_actel_check
- https://github.com/sot/ska_testr/tree/master/packages/fep1_mong_check
- https://github.com/sot/ska_testr/tree/master/packages/psmc_check

These tests are run:
- every midnight using all Ska packages in their corresponding master branches.
- for each Ska release candidate
- after each release
but perhaps we can run them at better times for you.

Since these tests take some time to run, I think it is best if you help to determine exactly how we run them, so you also benefit from these extra test runs. Could this save you time in the long run? Would you benefit if these tests are run at other times?

**Review by Gregg140 — APPROVED** [review]
Looks good

**Review by jazan12 — APPROVED** [review]

**Comment by jzuhone** [comment]
@javierggt with this update, all of the tests you mentioned above would now be run from the ``acis_thermal_check`` package, and the packages you list would be removed entirely.

**Comment by Gregg140** [comment]
Checked the "Support eclipses", "Fixing some bugs" and "Doc updates". All still looks good.

**Pull request merged**
