### PR TITLE
Replacing Chandra.Time with CxoTime

### PR DESCRIPTION
**Pull request by jzuhone**
## Description

This PR replaces the use of `Chandra.Time` for computing CXC times with `CxoTime`. 

## Testing

- [x] Passes unit tests on macOS 
- [ ] Functional testing

### CODE REVIEW

**Review by taldcroft — APPROVED** [review]
This looks fine to me.

**Review by Gregg140 — APPROVED** [review]
This PR looks good

**Comment by taldcroft** [comment]
Has this been OBE?  I had thought the replacement was already done.

**Comment by jzuhone** [comment]
@taldcroft yes, this is obsolete now but I forgot to change the status.

**Pull request closed without merging**
